PREFIX glycandata: <http://glycandata.glygen.org/glycandata#>

SELECT (?accession  as ?GlyTouCanAccession)
       (?value as ?BCSDBAccession)
WHERE {
  ?glycan glycandata:accession ?accession .
  ?ann1 glycandata:property "BCSDB" .
  ?ann1 glycandata:value ?value .
  ?ann1 glycandata:hasglycan ?glycan
}
ORDER BY ?accession ?value
