PREFIX glycandata: <http://glyomics.org/glycandata#>

SELECT ?GlyTouCanAccession ?Level ?Classification ?Source ?SourceID
WHERE {
  ?glycan glycandata:accession ?GlyTouCanAccession .
  ?ann1 glycandata:type "Classification" .
  ?ann1 glycandata:property ?Level .
  ?ann1 glycandata:value ?Classification .
  ?ann1 glycandata:hasglycan ?glycan
  OPTIONAL {
    ?ann1 glycandata:source ?Source .
    ?ann1 glycandata:sourceid ?SourceID .
  }
  FILTER(?Level = "GlycanType" || ?Level = "GlycanSubtype")
}
ORDER BY ?GlyTouCanAccession ?Level ?Classification ?Source ?SourceID
