PREFIX glycandata: <http://glycandata.glygen.org/glycandata#>

SELECT ?GlyTouCanAccession ?Level ?Classification ?Source ?SourceID
WHERE {
  ?glycan glycandata:accession ?GlyTouCanAccession .
  ?ann1 glycandata:type "Classification" .
  ?ann1 glycandata:property ?Level .
  ?ann1 glycandata:value ?Classification .
  ?ann1 glycandata:hasglycan ?glycan
  OPTIONAL {
    ?ann1 glycandata:source ?Source .
    ?ann1 glycandata:sourceid ?SourceID .
  }
  FILTER(regex(?Level,"^Glycan(Type|Subtype)$"))
}
ORDER BY ?GlyTouCanAccession ?Level ?Classification ?Source ?SourceID
