PREFIX glycandata: <http://glycandata.glygen.org/glycandata#>

SELECT (?accession  as ?GlyTouCanAccession)
       (?uniprot as ?Enzyme_UniProtAccession)
       (?gene as ?Enzyme_GeneName)
       (?geneid as ?Enzyme_GeneID)
       (?taxid as ?Enzyme_TaxonomyID)
WHERE {
  ?glycan glycandata:accession ?accession .
  ?ann1 glycandata:property "EnzymeDetails" .
  ?ann1 glycandata:value ?value .
  ?ann1 glycandata:hasglycan ?glycan
  BIND(STRBEFORE(?value,":") as ?uniprot)
  BIND(STRAFTER(?value,":") as ?remainder1)
  BIND(STRBEFORE(?remainder1,":") as ?gene)
  BIND(STRAFTER(?remainder1,":") as ?remainder2)
  BIND(STRBEFORE(?remainder2,":") as ?geneid)
  BIND(STRAFTER(?remainder2,":") as ?taxid)
}
ORDER BY ?accession ?taxid ?gene
