PREFIX glycandata: <http://glycandata.glygen.org/glycandata#>

SELECT (?accession  as ?GlyTouCanAccession)
       (?value as ?GlycomeDBID)
WHERE {
  ?glycan a glycandata:Glycan . 
  ?glycan glycandata:accession ?accession .
  ?ann0 glycandata:property "GlyGen" .
  ?ann0 glycandata:hasglycan ?glycan .
  ?ann1 glycandata:property "GlycomeDB" .
  ?ann1 glycandata:value ?value .
  ?ann1 glycandata:hasglycan ?glycan
}
