PREFIX glycandata: <http://glyomics.org/glycandata#>

SELECT DISTINCT
       (?accession  as ?GlyTouCanAccession)
       (?value as ?GLYCOSCIENCESdeAccession)
WHERE {
  ?glycan glycandata:accession ?accession .
  ?ann1 glycandata:type "CrossReference" .
  ?ann1 glycandata:property "GLYCOSCIENCES.de" .
  ?ann1 glycandata:value ?value .
  ?ann1 glycandata:hasglycan ?glycan
} 
ORDER BY ?accession ?value
