PREFIX glycandata: <http://glyomics.org/glycandata#>

SELECT (?accession  as ?GlyTouCanAccession)
WHERE {
  ?glycan glycandata:accession ?accession .
  ?ann1 glycandata:property "GNOme" .
  ?ann1 glycandata:type "CrossReference" .
  ?ann1 glycandata:hasglycan ?glycan
}
ORDER BY ?accession
