PREFIX glycandata: <http://glycandata.glygen.org/glycandata#>

SELECT (?accession  as ?GlyTouCanAccession)
       (?property as ?Species)
       (?value as ?Value)
WHERE {
  ?glycan glycandata:accession ?accession .
  ?ann1 glycandata:type "Species" .
  ?ann1 glycandata:property ?property .
  ?ann1 glycandata:value ?value .
  ?ann1 glycandata:hasglycan ?glycan
} ORDER BY ?accession ?property ?value
