PREFIX glycandata: <http://glyomics.org/glycandata#>

SELECT (?accession  as ?GlyTouCanAccession)
       (?value as ?UniCarbDBID)
WHERE {
  ?glycan glycandata:accession ?accession .
  ?ann1 glycandata:property "UniCarb-DB" .
  ?ann1 glycandata:value ?value .
  ?ann1 glycandata:hasglycan ?glycan
}
ORDER BY ?accession ?value
